language: cpp
sudo: required
dist: trusty
compiler:
  - g++
os:
  - linux
before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq
install:
  - sudo apt-get install cmake
  - sudo apt-get install -qq g++-5
  - sudo update-alternatives --install /usr/bin/gcov gcov /usr/bin/gcov-5 90
env:
  - BUILD_TYPE=debug
  - BUILD_TYPE=release
script:
  - ./build.sh
  - ./travis_qmake_gcc_cpp11_gcov
  - ./get_code_cov.sh
after_success: 
  - bash <(curl -s https://codecov.io/bash)